metricbeat.modules:
  - module: nginx
    metricsets: ["stubstatus"]
    enabled: true
    period: ${OPENVIDU_PRO_STATS_MONITORING_INTERVAL}s
    hosts: ["http://127.0.0.1"]
    server_status_path: "nginx_status"
  - module: system
    metricsets:
      - cpu
      - diskio
      - memory
      - network
      - filesystem
      - fsstat
      #- process
      - process_summary
      - uptime
    filesystem.ignore_types: [nfs, smbfs, autofs, devtmpfs, devpts, hugetlbfs, tmpfs, sysfs, securityfs, cgroup2, cgroup, pstore, debugfs, configfs, fusectl, proc, fuse.lxcfs, squashfs]
    processes: ['.*']
    #    process.include_top_n:
    #      by_cpu: 2
    #      by_memory: 2
    processors:
      - drop_event:
           when:
              or:
                - regexp:
                      system.network.name: '^(veth|lo|docker|br-)($|)'
                - regexp:
                      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host)($|/)'
                - regexp:
                      system.filesystem.mount_point: '^/hostfs/(sys|cgroup|proc|dev|etc|host)($|/)'
    enabled: true
    period: ${OPENVIDU_PRO_STATS_MONITORING_INTERVAL}s
    cpu.metrics: [normalized_percentages]
fields:
  ip: "${MEDIA_NODE_IP}"
  cluster_id: ${OPENVIDU_PRO_CLUSTER_ID:${DOMAIN_OR_PUBLIC_IP:undefined}}
  node_id: master_${AWS_INSTANCE_ID:${OPENVIDU_PRO_CLUSTER_ID:${DOMAIN_OR_PUBLIC_IP:undefined}}}
  node_role: masternode
pipeline:
  queue.mem.events: 0
setup.ilm.enabled: false
